/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lk.redwolfdynamic.rsm.admin.gui;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import lk.redwolfdynamic.rsm.admin.panel.Dashboard;
import lk.redwolfdynamic.rsm.admin.panel.EmployeeManagement;
import lk.redwolfdynamic.rsm.admin.panel.FinancialManagement;
import lk.redwolfdynamic.rsm.admin.panel.InventoryManagement;
import lk.redwolfdynamic.rsm.admin.panel.Notifications;
import lk.redwolfdynamic.rsm.admin.panel.Reports_Analysis;
import lk.redwolfdynamic.rsm.admin.panel.RoleManagement;
import lk.redwolfdynamic.rsm.admin.panel.UserManagement;
import lk.redwolfdynamic.rsm.admin.panel.adminSetings;

/**
 *
 * @author Umesh_Sandeepa
 */
public class AdminHome extends javax.swing.JFrame {

    private Dashboard dashboard;
    private UserManagement usemanagement;
    private RoleManagement rolemanaagement;
    private EmployeeManagement employeemanagement;
    private InventoryManagement inventorymanagement;
    private FinancialManagement financialManagement;
    private Reports_Analysis reports_analysis;
    private Notifications notifications;
    private CardLayout MainCommenpanel;

    /**
     * Creates new form Dashboard
     */
    public AdminHome() {
        initComponents();
        loadpanels();

    }

    private void loadpanels() {

        if (MainCommenpanel == null && commenPanel.getLayout() instanceof CardLayout) {
            MainCommenpanel = (CardLayout) commenPanel.getLayout();
        }

        this.dashboard = new Dashboard();
        this.usemanagement = new UserManagement();
        this.rolemanaagement = new RoleManagement();
        this.employeemanagement = new EmployeeManagement();
        this.inventorymanagement = new InventoryManagement();
        this.financialManagement = new FinancialManagement();
        this.notifications = new Notifications();

        this.reports_analysis = new Reports_Analysis();

        this.commenPanel.add(dashboard, "dashboard_panel");
        this.commenPanel.add(usemanagement, "user_management");
        this.commenPanel.add(rolemanaagement, "role_management");
        this.commenPanel.add(employeemanagement, "employee_management");
        this.commenPanel.add(inventorymanagement, "inventory_management");
        this.commenPanel.add(financialManagement, "financial_management");
        this.commenPanel.add(reports_analysis, "reports_analysis");
        this.commenPanel.add(notifications, "notifications");

      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        full_name = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        adminrportsanalysis = new javax.swing.JButton();
        adminRolemanagement = new javax.swing.JButton();
        adminUsermanagement = new javax.swing.JButton();
        adminDashboard = new javax.swing.JButton();
        admininventorymanagement = new javax.swing.JButton();
        adminfinancialmanagement = new javax.swing.JButton();
        adminNotifications = new javax.swing.JButton();
        adminSettings = new javax.swing.JButton();
        adminLogout = new javax.swing.JButton();
        adminEmployyesmanagement = new javax.swing.JButton();
        topPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        commenPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Revenue Manegement System ");

        sidePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/redwolfdynamic/rsm/img/admin-panel (3).png"))); // NOI18N

        full_name.setBackground(new java.awt.Color(0, 0, 0));
        full_name.setFont(new java.awt.Font("IBM Plex Sans SemiCondensed", 0, 14)); // NOI18N
        full_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        full_name.setText("Full Name");

        email.setBackground(new java.awt.Color(0, 0, 0));
        email.setFont(new java.awt.Font("IBM Plex Sans SemiCondensed", 0, 14)); // NOI18N
        email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        email.setText("Email ");

        id.setBackground(new java.awt.Color(0, 0, 0));
        id.setFont(new java.awt.Font("IBM Plex Sans SemiCondensed", 0, 14)); // NOI18N
        id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id.setText("ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(full_name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(full_name, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        adminrportsanalysis.setFont(new java.awt.Font("IBM Plex Sans SemiCondensed", 0, 18)); // NOI18N
        adminrportsanalysis.setText("Reports & Analysis");
        adminrportsanalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminrportsanalysisActionPerformed(evt);
            }
        });

        adminRolemanagement.setFont(new java.awt.Font("IBM Plex Sans SemiCondensed", 0, 18)); // NOI18N
        adminRolemanagement.setText("Role Management");
        adminRolemanagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminRolemanagementActionPerformed(evt);
            }
        });

        adminUsermanagement.setFont(new java.awt.Font("IBM Plex Sans SemiCondensed", 0, 18)); // NOI18N
        adminUsermanagement.setText("User Management");
        adminUsermanagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminUsermanagementActionPerformed(evt);
            }
        });

        adminDashboard.setFont(new java.awt.Font("IBM Plex Sans SemiCondensed", 0, 18)); // NOI18N
        adminDashboard.setText("Dashboard");
        adminDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminDashboardActionPerformed(evt);
            }
        });

        admininventorymanagement.setFont(new java.awt.Font("IBM Plex Sans SemiCondensed", 0, 18)); // NOI18N
        admininventorymanagement.setText("Inventory Management ");
        admininventorymanagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admininventorymanagementActionPerformed(evt);
            }
        });

        adminfinancialmanagement.setFont(new java.awt.Font("IBM Plex Sans SemiCondensed", 0, 18)); // NOI18N
        adminfinancialmanagement.setText("Financial Management ");
        adminfinancialmanagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminfinancialmanagementActionPerformed(evt);
            }
        });

        adminNotifications.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/redwolfdynamic/rsm/img/icons8-notification-45.png"))); // NOI18N
        adminNotifications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminNotificationsActionPerformed(evt);
            }
        });

        adminSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/redwolfdynamic/rsm/img/icons8-settings-50.png"))); // NOI18N
        adminSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminSettingsActionPerformed(evt);
            }
        });

        adminLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/redwolfdynamic/rsm/img/icons8-logout-30.png"))); // NOI18N
        adminLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLogoutActionPerformed(evt);
            }
        });

        adminEmployyesmanagement.setFont(new java.awt.Font("IBM Plex Sans SemiCondensed", 0, 18)); // NOI18N
        adminEmployyesmanagement.setText("Employees Management");
        adminEmployyesmanagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminEmployyesmanagementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminrportsanalysis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminRolemanagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminUsermanagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(admininventorymanagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminfinancialmanagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addComponent(adminNotifications, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adminSettings)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(adminEmployyesmanagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(adminDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adminUsermanagement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adminRolemanagement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(adminEmployyesmanagement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(admininventorymanagement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adminfinancialmanagement, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adminrportsanalysis, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(adminNotifications, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminSettings, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        topPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        jLabel2.setFont(new java.awt.Font("IBM Plex Sans SemiCondensed", 1, 48)); // NOI18N
        jLabel2.setText("Revenue Management System");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(539, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addContainerGap())
        );

        commenPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        commenPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(commenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(commenPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adminRolemanagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminRolemanagementActionPerformed
        this.MainCommenpanel.show(commenPanel, "role_management");
    }//GEN-LAST:event_adminRolemanagementActionPerformed

    private void adminUsermanagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminUsermanagementActionPerformed
        this.MainCommenpanel.show(commenPanel, "user_management");
    }//GEN-LAST:event_adminUsermanagementActionPerformed

    private void adminDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminDashboardActionPerformed
        this.MainCommenpanel.show(commenPanel, "dashboard_panel");
    }//GEN-LAST:event_adminDashboardActionPerformed

    private void adminrportsanalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminrportsanalysisActionPerformed
        this.MainCommenpanel.show(commenPanel, "reports_analysis");
    }//GEN-LAST:event_adminrportsanalysisActionPerformed

    private void admininventorymanagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admininventorymanagementActionPerformed
        this.MainCommenpanel.show(commenPanel, "inventory_management");
    }//GEN-LAST:event_admininventorymanagementActionPerformed

    private void adminfinancialmanagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminfinancialmanagementActionPerformed
        this.MainCommenpanel.show(commenPanel, "financial_management");
    }//GEN-LAST:event_adminfinancialmanagementActionPerformed

    private void adminLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLogoutActionPerformed

        int choice = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to log out?",
                "Logout",
                JOptionPane.YES_NO_OPTION);

        if (choice == JOptionPane.YES_OPTION) {

            this.dispose();

            AdminLogin login = new AdminLogin();
            login.setVisible(true);
        }
    }//GEN-LAST:event_adminLogoutActionPerformed

    private void adminEmployyesmanagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminEmployyesmanagementActionPerformed
        this.MainCommenpanel.show(commenPanel, "employee_management");
    }//GEN-LAST:event_adminEmployyesmanagementActionPerformed

    private void adminSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminSettingsActionPerformed
        adminSetings setings = new adminSetings(this, true);
        setings.setVisible(true);

    }//GEN-LAST:event_adminSettingsActionPerformed

    private void adminNotificationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminNotificationsActionPerformed
        this.MainCommenpanel.show(commenPanel, "notifications");
    }//GEN-LAST:event_adminNotificationsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatDarkLaf.setup();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminDashboard;
    private javax.swing.JButton adminEmployyesmanagement;
    private javax.swing.JButton adminLogout;
    private javax.swing.JButton adminNotifications;
    private javax.swing.JButton adminRolemanagement;
    private javax.swing.JButton adminSettings;
    private javax.swing.JButton adminUsermanagement;
    private javax.swing.JButton adminfinancialmanagement;
    private javax.swing.JButton admininventorymanagement;
    private javax.swing.JButton adminrportsanalysis;
    private javax.swing.JPanel commenPanel;
    private javax.swing.JLabel email;
    private javax.swing.JLabel full_name;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
